Fix #16 (Responsibilities mixup when resolving with Promise)
async-interop/promise pull request #22
Opened 2016-12-22 17:22 UTC by bwoebi

2016-12-22 17:33 UTC, trowski approved these changes

2016-12-22 18:57 UTC, kelunik commented on META.md
> +The specification recommends whenever the result of a `Promise` is being set to another `Promise`, it should be set to the value the other `Promise` has been or will be resolved with.
_recommends_ doesn't fit here IMO.

2016-12-22 19:11 UTC, kelunik requested changes

2016-12-22 19:11 UTC, kelunik commented on META.md
>  ## Creation of Promises
I'd just rename this section to `Resolution of Promises` and remove the below header, so combine it into one section.

2016-12-22 19:11 UTC, kelunik commented on META.md
> +The specification recommends whenever the result of a `Promise` is being set to another `Promise`, it should be set to the value the other `Promise` has been or will be resolved with.
The result of a `Promise` can never be set to another `Promise`, as that's not allowed.

2016-12-22 19:47 UTC, bwoebi commented on META.md
> +The specification recommends whenever the result of a `Promise` is being set to another `Promise`, it should be set to the value the other `Promise` has been or will be resolved with.
That's true and said in the README. This is the META document, giving a recommendation.

Feel free to push with better wording.

2016-12-23 17:31 UTC, bwoebi commented
Closing in favor of much better wording in #24.

2016-12-23 17:31 UTC, closed without merging